### ISSUE TITLE
Missing WriteAllTextAsync

### ISSUE THREAD

**Issue by jjindrich** [PCLExt/PCLExt.FileStorage#1]
Please add from original project FileExtensions.cs
https://github.com/dsplaisted/PCLStorage/blob/master/src/PCLStorage.Abstractions/FileExtensions.cs

**Comment by Aragas** [comment]
It should be available in all frameworks, what do you use?
https://github.com/PCLExt/PCLExt.FileStorage/blob/94d04d75c948d365df9d56a08d1806a8dff4870b/src/PCLExt.FileStorage.Portable111/Extensions/FileExtensions.cs#L67

**Comment by jjindrich** [comment]
thanks, finally using IsolatedStorageFile directly from dotnetstandard2
