### ISSUE TITLE
Make every CancellationToken optionals

### ISSUE THREAD

**Issue by Binnette** [PCLExt/PCLExt.FileStorage#13]
Hi can you please make every "CancellationToken" optionals ?

Here are some methods where CancellationToken is not optional :

-BaseFile.ReadAllBytesAsync
-BaseFile.WriteAllBytesAsync

Thank you :blush:

**Comment by Aragas** [comment]
Done

**Comment by Binnette** [comment]
Thanks 👍 👍 👍
