### ISSUE TITLE
CreateFile freezes on UWP but not on Android.

### ISSUE THREAD

**Issue by asusralis** [PCLExt/PCLExt.FileStorage#16]
`IFile file = 
                new FolderFromPath(_rootPath + dirSeperator + path)
                .CreateFile(name, CreationCollisionOption.ReplaceExisting);`

This freezes on UWP but not on Android. All CreationCollisionOption choices freeze. Note that the file is created, but then the application freezes without throwing an exception.

**Comment by Aragas** [comment]
@ArtjomP please look at this

**Comment by ArtjomP** [comment]
@asusralis  It can be, please use 
`
var folder = new FolderFromPath(_rootPath + dirSeperator + path);
IFile file = await folder.CreateFile(name, CreationCollisionOption.ReplaceExisting);
`
or call this method from non UI thread.

**Comment by ArtjomP** [comment]
or 
`
var folder = new FolderFromPath(_rootPath + dirSeperator + path);
IFile file = await folder.CreateFile(name, CreationCollisionOption.ReplaceExisting).ConfigureAwait(false);
`

**Comment by asusralis** [comment]
Thanks for the reply - it works. Is there a limitation on why you can't create a file on UWP in a non-task method?

**Comment by ArtjomP** [comment]
CreateFile calls async method inside [https://github.com/PCLExt/PCLExt.FileStorage/blob/master/src/PCLExt.FileStorage.UWP/StorageFolderImplementation.cs](url) and it can block you UI if you call it from UI thread. You can find some explanation here: [https://stackoverflow.com/questions/14526377/why-does-this-async-action-hang](url)
