### ISSUE TITLE
Add some documentation

### ISSUE THREAD

**Issue by Binnette** [PCLExt/PCLExt.FileStorage#2]
Hi,

Can you please add some documentation in your README.md ?
May be, just copy/paste orignal plugin library.

Have you add some new methods yet ?

**Comment by Binnette** [comment]
In v1.0.9.1 : you added some methods which one ? (Please add them in your README.md)

**Comment by Aragas** [comment]
See in https://github.com/PCLExt/PCLExt.FileStorage/commit/46fa408d342c92e44e8b2fb0c684c0d43ef9c9d9.
Added documentation site with some examples.
P.S. Thanks for the tip!

**Comment by Binnette** [comment]
Your home page is a bit "confusing" and too empty
![image](https://user-images.githubusercontent.com/6597721/32622530-6e0df4bc-c583-11e7-8518-c01edd1d82d4.png)

Please in this home page add A BIG LINK to the API documenattion
Please also add links to your articles :
- How to create a log file with PCLExt.FileStorage
- How to create a JSON file with PCLExt.FileStorage

Also, in your homepage, add available methods for File & for Folder
![image](https://user-images.githubusercontent.com/6597721/32622677-eecd60d8-c583-11e7-8360-99f4eae88b32.png)

In fact, developpers, just want to know if your library can copy, delete, create, rename, ... files & folder :smiley_cat: 

Also, add a link to go back to your project github page

**Comment by Aragas** [comment]
Added a home page
Articles are available from the table of content on top
API's index page states about interface and abstract files, they can see the available methods there
