### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by rogercorrea** [PCLExt/PCLExt.FileStorage#22]
Please,

A error occur for me when I try install:

Could not install package 'PCLExt.FileStorage 1.3.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I use Xamarin.Forms in Visual Studio 2015.

**Comment by Aragas** [comment]
I'm sorry for the long answer.
The project targets only profile111, but it seems 259 is popular too, so I'll add it

**Comment by Aragas** [comment]
Fixed by 5e771903805e3495c284a6a7fe76727175f2531e
