### ISSUE TITLE
Feature request for KnownFolders such as Picture, Music, Movies etc.

### ISSUE THREAD

**Issue by jaladaGmbH** [PCLExt/PCLExt.FileStorage#23]
For PCLStorage exists a Plugin for special folder  such as Picture, Music, Movies etc.
https://github.com/picolyl/XamarinPlugins.PCLSpecialFolder

It would be nice to have the same functionality in your excellent framework.

**Comment by Aragas** [comment]
Okay, lemme do a note of what is implemented and not.
✓Local
✓Roaming
✓Temp
✗Cache
✓Documents
✗Pictures
✗Music
✗Video
✓App

**Comment by Aragas** [comment]
Done, check d221e2f26dd64f9d822d894a0c9c60389cb432d5. NuGet will be updated after we will be done with UWP.

**Comment by jaladaGmbH** [comment]
Hello Aragas 
at the moment I missed for my Media Player the standard folders for Music, Video and Pictures

The main problem for me is, that your UWP implementation is not public and the Windows.Storage.StorageFolder Path property for the special folders are empty . Under this circumstances the only way to use your framework is by copy StorageFolderImplementation and StorageFileImplementation. What I think is not a good solution?

I have attached the missing folder cs files as zip, so you can add them easily to your next release.

Best regards
Andreas

[Folders.zip](https://github.com/PCLExt/PCLExt.FileStorage/files/2142566/Folders.zip)

**Comment by jaladaGmbH** [comment]
Many thanks
