### ISSUE TITLE
Add release and tags

### ISSUE THREAD

**Issue by Binnette** [PCLExt/PCLExt.FileStorage#3]
Can you please add release and tags corresponding to your nuget versions :
* 1.3.1
* 1.3.0
* 1.2.1.1
* 1.2.0.1
* 1.1.4

**Comment by Aragas** [comment]
Done. Thanks for the tip!

**Comment by Binnette** [comment]
Perfect ! This way users can see what you've done on your lib :+1:

**Comment by Binnette** [comment]
Some comments :
- In v1.0.9: "aded" => "added"
- In v1.0.9: "Removed Storage.cs" why did you remove this file ?
- In v1.1.3: you "Fixed GetFiles". what was the problem ? (Can you add a short description or create an issue to describe the problem and link the issue in release description. And after close the issue. Issue link can be done with #IssueNumber)

**Comment by Aragas** [comment]
* Typos are bad, but I don't think I should force push just for fixing this
* It was partially answered in the first part of the new README. FileStorage is not just a fork of PCLStorage anymore, the API was changed, it uses a different approach now. The earlier versions like the 1.0.x.x ones are still similar to PCLStorage. They even included some fixes from PCLStorage that were not merged if I remember correct
For some shitty examples, look at 
https://github.com/P3D-Legacy/P3D-Legacy-Launcher/tree/master/P3D-Legacy%20Launcher/Storage
https://github.com/PokeD/PokeD.Server/tree/master/PokeD.Server/Storage
* Look at the commit. It was a default wildcard pattern typo, I forgot to add it in previous commit guess. These kind of issues should not get some kind of a full report
