### ISSUE TITLE
Missing UWP support

### ISSUE THREAD

**Issue by zimmerrol** [PCLExt/PCLExt.FileStorage#31]
In version `1.4.0` support for `UWP` had been removed. Until now, it hasn't been added again. Is there a timeline when `UWP` will be supported again?

**Comment by ArtjomP** [comment]
Check this package: [pt.PCLExt.FileStorage](https://www.nuget.org/packages/pt.PCLExt.FileStorage/)

It is my publishing of this repo. I use it in my UWP projects

**Comment by Aragas** [comment]
Should be fixed by #32
