### ISSUE TITLE
BaseFile.MoveAsync(string newPath)

### ISSUE THREAD

**Issue by Binnette** [PCLExt/PCLExt.FileStorage#9]
Hi, this method is not working.
It removes the file available at BaseFile.Path, but it does NOT copy the file in "newPath".

Can you try this code, and check that the file is correctly moved :
```
var path = "/storage/emulated/0/Android/data/test/temp/20171114.jpg";
var newPath = "/storage/emulated/0/Android/data/test/20171114.jpg";
var file = new FileFromPath(path);
var newFile = await file.MoveAsync(newPath);
// OK newFile.Path is egal to newPath
// But there is no file with path "/storage/emulated/0/Android/data/test/20171114.jpg"
// File is deleted but not moved :(
```

I use :
* .Net Standard 2.0 Class library
* PCLEct.FileStorage 1.3.1
* Xamarin.forms
* Device with Android 6.0

Please test this code, and tell me if the file is really moved on an android device.
(Or maybe you can test it in a windows console app...)

**Comment by Aragas** [comment]
Seems to be working.
Because the operation is async, maybe the task could not finish before you terminate your app.
To check this, either replace  ```var newFile = await file.MoveAsync(newPath);``` with ```var newFile = file.MoveAsync(newPath).Result;``` or ```var newFile = file.Move(newPath);```

**Comment by Binnette** [comment]
Thanks, i will test it soon :+1:

**Comment by Binnette** [comment]
My bad ! Of course your library move the file in async correctly. But I was deleting the moved file in my code few instructions later :sweat_smile::nerd_face::muscle::see_no_evil:
